# Generated by Django 4.2.3 on 2023-08-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("secretary", "0002_alter_secretary_proile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secretary",
            name="proile_picture",
            field=models.URLField(blank=True, null=True),
        ),
    ]
