# Generated by Django 4.2.3 on 2023-08-24 04:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("announcement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
