# Generated by Django 4.2.3 on 2023-07-26 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizer", "0002_eventhead_organizingteam_and_more"),
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Speaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=200)),
                ("bio", models.CharField(max_length=2000)),
                ("image", models.ImageField(blank=True, upload_to="images/")),
            ],
        ),
        migrations.RemoveField(
            model_name="event",
            name="organizers",
        ),
        migrations.AddField(
            model_name="event",
            name="fb_link",
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="fee",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="event",
            name="ig_link",
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="max_participants",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="registration_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="registration_start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="organizer.organizingteam",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="twitter_link",
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(blank=True, max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="meet_link",
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="yt_link",
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="type",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
