# Generated by Django 4.2.3 on 2023-07-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0003_event_created_at_event_misc_links_event_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
