# Generated by Django 4.2.3 on 2023-08-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0004_event_is_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="judge",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="mentor",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="speaker",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="website",
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
    ]
