# Generated by Django 4.2.3 on 2023-08-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0005_alter_judge_image_alter_mentor_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="speakers",
            field=models.ManyToManyField(blank=True, to="event.speaker"),
        ),
    ]
