# Generated by Django 4.2.3 on 2023-08-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0006_event_speakers"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_team_event",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="template",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
