# Generated by Django 4.2.3 on 2023-08-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0007_event_is_team_event_event_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventpicture",
            name="image",
            field=models.URLField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name="judge",
            name="image",
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name="mentor",
            name="image",
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name="speaker",
            name="image",
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="logo",
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
    ]
