# Generated by Django 4.2.3 on 2023-08-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0008_alter_eventpicture_image_alter_judge_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
