# Generated by Django 4.2.3 on 2023-08-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0009_alter_event_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="website_links",
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
    ]
