# Generated by Django 4.2.3 on 2023-08-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0010_event_website_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="header_image",
            field=models.ImageField(blank=True, null=True, upload_to="events"),
        ),
    ]
