# Generated by Django 4.2.3 on 2023-07-26 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventHead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("handle", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=200)),
                ("profile_picture", models.ImageField(upload_to="profile_pictures")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrganizingTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_head",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizer.eventhead",
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="organizer",
            old_name="handle",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="organizer",
            name="profile_picture",
        ),
        migrations.RemoveField(
            model_name="organizer",
            name="user",
        ),
        migrations.AddField(
            model_name="organizer",
            name="email",
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="organizer",
            name="phone",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="organizer",
            name="role",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name="Role",
        ),
        migrations.AddField(
            model_name="organizingteam",
            name="organizers",
            field=models.ManyToManyField(to="organizer.organizer"),
        ),
    ]
