# Generated by Django 4.2.3 on 2023-08-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizer", "0002_eventhead_organizingteam_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventhead",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures"
            ),
        ),
    ]
