# Generated by Django 4.2.3 on 2023-08-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizer", "0003_alter_eventhead_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizingteam",
            name="organizers",
            field=models.ManyToManyField(blank=True, to="organizer.organizer"),
        ),
    ]
