# Generated by Django 4.2.3 on 2023-08-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizer", "0006_alter_eventhead_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventhead",
            name="phone",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
