# Generated by Django 4.2.3 on 2023-07-27 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0002_speaker_remove_event_organizers_event_fb_link_and_more"),
        ("student", "0003_studenteventapplication_artifacts_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("application_date", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="event.event"
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(related_name="teams", to="student.student"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentTeamEventApplictaion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("application_date", models.DateTimeField(auto_now_add=True)),
                ("artifacts", models.URLField(blank=True, max_length=600, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="event.event"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.studentteam",
                    ),
                ),
            ],
        ),
    ]
