# Generated by Django 4.2.3 on 2023-07-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0004_studentteam_studentteameventapplictaion"),
    ]

    operations = [
        migrations.AddField(
            model_name="studenteventapplication",
            name="custom_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentteameventapplictaion",
            name="custom_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
