# Generated by Django 4.2.3 on 2023-07-29 07:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0005_studenteventapplication_custom_data_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentteam",
            name="application_date",
        ),
    ]
