# Generated by Django 4.2.3 on 2023-07-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0004_event_is_approved"),
        ("student", "0006_remove_studentteam_application_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="events",
            field=models.ManyToManyField(
                blank=True, related_name="participants", to="event.event"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures"
            ),
        ),
    ]
