# Generated by Django 4.2.3 on 2023-08-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0007_alter_student_date_of_birth_alter_student_events_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentteam",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="teams", to="student.student"
            ),
        ),
    ]
