# Generated by Django 4.2.3 on 2023-08-10 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0009_alter_event_description"),
        ("student", "0011_winningteam"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentteam",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="event.event",
            ),
        ),
    ]
