# Generated by Django 4.2.3 on 2023-08-13 08:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0012_alter_studentteam_event"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studenteventapplication",
            old_name="stduent",
            new_name="student",
        ),
    ]
